name: Build Project

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    name: '[${{ matrix.os }}] build plugin'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Write Gradle build properties to `~/.gradle/gradle.properties`
        run: |
          mkdir -p ~/.gradle
          printf "org.gradle.jvmargs=-Xmx3G -XX:+UseParallelGC\n" >> ~/.gradle/gradle.properties
          printf "org.gradle.vfs.watch=false\n" >> ~/.gradle/gradle.properties
        shell: bash

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - uses: gradle/wrapper-validation-action@v1

      - uses: gradle/gradle-build-action@v2

      - run: ./gradlew assemble

      - run: ./gradlew check

      - run: ./gradlew publishToMavenLocal

      - run: ./gradlew publishPlugins -m

      - run: git diff --exit-code

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-results-${{ matrix.os }}
          path: "${{ github.workspace }}/**/build/reports/tests"

  provide-agp-version-matrix:
    runs-on: ubuntu-latest
    outputs:
      agp-versions: ${{ steps.build-agp-matrix.outputs.agp-versions }}
    steps:
      - id: agp-version-finder
        uses: usefulness/agp-version-finder-action@v1

      - id: build-agp-matrix
        run: |
          echo 'agp-versions=["${{ steps.agp-version-finder.outputs.latest-stable }}", "${{ steps.agp-version-finder.outputs.latest-alpha }}"]' >> $GITHUB_OUTPUT

  integration-tests-android:
    runs-on: ubuntu-latest
    needs:
      - provide-agp-version-matrix
    strategy:
      fail-fast: false
      matrix:
        gradle: [ current, release-candidate ]
        java: [ 21 ]
        agp: ${{ fromJSON(needs.provide-agp-version-matrix.outputs.agp-versions) }}

    name: '[android] Gradle: ${{ matrix.gradle }}, Java: ${{ matrix.java }}, AGP: ${{ matrix.agp }}'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Write Gradle build properties to `~/.gradle/gradle.properties`
        run: |
          mkdir -p ~/.gradle
          printf "org.gradle.jvmargs=-Xmx3G -XX:+UseParallelGC\n" >> ~/.gradle/gradle.properties
          printf "org.gradle.vfs.watch=false\n" >> ~/.gradle/gradle.properties
        shell: bash

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - uses: gradle/gradle-build-action@v2
        continue-on-error: true
        with:
          build-root-directory: sample
          gradle-version: ${{ matrix.gradle }}
          arguments: build -PagpVersion=${{ matrix.agp }} --continue

      - name: Upload reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: "sample-reports-${{ matrix.gradle }}-${{ matrix.java }}-${{ matrix.agp }}"
          path: "${{ github.workspace }}/**/build/reports/"
